name: Package

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Lint
        run: |
          poetry run isort --profile black .
          poetry run black .
      - name: Test
        run: poetry run pytest --doctest-modules

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/') || github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Build
        run: poetry build
      - name: Tag nightly
        if: github.ref_name == 'main'
        uses: EndBug/latest-tag@latest
        with:
          ref: nightly
          description: Nightly version
      - name: Rename dist files
        if: github.ref_name == 'main'
        run: |
          version=$(poetry run python -c "import wiki_vector_search as wvs; print(wvs.__version__)")
          mv dist/wiki_vector_search-$version-py3-none-any.whl dist/wiki_vector_search-nightly-py3-none-any.whl
          mv dist/wiki_vector_search-$version.tar.gz dist/wiki_vector_search-nightly.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.ref_name == 'main' }}
          tag_name: ${{ github.ref_name == 'main' && 'nightly' || github.ref_name }}
          generate_release_notes: true
          files: dist/*
