name: Package

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install deps
        run: poetry install --all-extras
      - name: Lint
        run: |
          poetry run isort --profile black .
          poetry run black .
      - name: Test
        run: poetry run pytest --doctest-modules

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "poetry"
      - name: Install deps
        run: poetry install --all-extras
      - name: Build
        run: poetry build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*
